name: flutter_ipa_export
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.7.0
  curved_labeled_navigation_bar: ^2.0.2
  flutter_svg: ^1.1.6
  linear_progress_bar: ^1.1.0
  jalali_table_calendar_plus: ^1.1.1
  flutter_to_pdf: ^0.2.0
  persian_datetime_picker: ^3.0.2
  data_table_2: ^2.5.15
  # device_info_plus: ^9.1.2
  flutter_local_notifications: ^17.2.3
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  file_picker: ^8.1.3
  path_provider: ^2.1.4
  cached_network_image: ^3.4.1
  shamsi_date: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
